name: 'AMI Terraform'

on:
  workflow_dispatch:
    branches:
      - "master"
    paths: 
      - "ami-terraform/**"
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: ami-terraform

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.ACCESSKEY }}
        aws-secret-access-key: ${{ secrets.SECRETACCESSKEY }}
        aws-region: us-east-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.9.8 

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.    
    - name: Terraform Init
      run: terraform init -backend-config="bucket=${{ secrets.S3_BACKEND_BUCKET}}" -backend-config="key=ami/${{ secrets.TF_STATE }}" -backend-config="region=us-east-1" -backend-config="dynamodb_table=${{ secrets.DYNAMO_DB_TABLE }}" 

    - name: Terraform Format
      run: terraform fmt -check

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: terraform plan 

      # On push to "master", build or change infrastructure according to Terraform configuration files
      # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
    - name: Terraform Apply
      run: terraform apply -auto-approve

    - name: Terraform State List
      run: terraform state list

    - name: Terraform Destroy
      run: terraform destroy -auto-approve
